### ISSUE TITLE
Docker Deploy

### ISSUE THREAD

**Issue by asteen27** [nexcess/ansible-role-tacacs#1]
@clwells 

Any reason to not use Docker or a combination of both Docker and Ansible to deploy this? I found some prebuilt containers for tac_plus.

I can start working on a docker compose file if you're good with that.

Thanks!

**Comment by clwells** [comment]
No, no reason not to.  Go ahead.  We'll actually do the deploy though as part of the NocWorx re-deploy.  that said I don't want tac_plus / nocworx to live together anymore.  They are breaking up :(,
